### ISSUE TITLE
Test app doesn't work (using defaults)

### ISSUE THREAD

**Issue by wrossmorrow** [scottylogan/passport-stanford#3]
I am running the test app, as a start, and getting the following error: 

    /home/ubuntu/samlnode/node_modules/passport/lib/authenticator.js:56
      if (!name) { throw new Error('Authentication strategies must have a name'); }
               ^

    Error: Authentication strategies must have a name
        at Authenticator.use (/home/ubuntu/samlnode/node_modules/passport/lib/authenticator.js:56:22)
        at Object.<anonymous> (/home/ubuntu/samlnode/index.js:46:10)
        at Module._compile (module.js:649:30)
        at Object.Module._extensions..js (module.js:660:10)
        at Module.load (module.js:561:32)
        at tryModuleLoad (module.js:501:12)
        at Function.Module._load (module.js:493:3)
        at Function.Module.runMain (module.js:690:10)
        at startup (bootstrap_node.js:194:16)
        at bootstrap_node.js:666:3

I've also added a `name` field to `saml` in `new suSAML.Strategy( ... )`, with no effect. The `README.md` file suggests a default `name` exists (`suSAML`).

**Comment by wrossmorrow** [comment]
I've gotten the app to run by including a name in the `passport.use` call in (I think) line 45: 

    passport.use( 'saml' , saml );

Any login attempts return "unauthorized" though. I can load other routes, but `login` fails.

**Comment by scottylogan** [comment]
Passport-Stanford tracks the SAML Relay State in a cookie, so you need to go to a protected page (like /profile), accept and use the cookies, and follow redirects, to get to the login page on the IdP:

```
% curl -{b,c}\ cookies.txt -v -L http://localhost:3000/profile/
> GET /profile/ HTTP/1.1
> Host: localhost:3000
> 
< HTTP/1.1 302 Found
< Location: /saml
< set-cookie: stanford=s%3AwOhSfcjY-FvKHJsCb0NfS3OvRnO53Hl5.LsvKZAvS0r9LXKZv9pvNgbkxYiNtVFC5ddDvYcnSR7k; Path=/; Expires=Tue, 24 Apr 2018 20:32:41 GMT; HttpOnly
< 
> GET /saml HTTP/1.1
> Host: localhost:3000
> Cookie: stanford=s%3AwOhSfcjY-FvKHJsCb0NfS3OvRnO53Hl5.LsvKZAvS0r9LXKZv9pvNgbkxYiNtVFC5ddDvYcnSR7k
> 
< HTTP/1.1 302 Found
< Location: https://login.itlab.stanford.edu/idp/profile/SAML2/Redirect/SSO?SAMLRequest=nZJPT%2BMwEMW%2FSuR74iSEf1ZTVKgQlViomi4HLshxpq0lxw6eCQvffp2USOylh72On%2F1%2B741nN5%2BtiT7Ao3a2ZFmSspv5DGVrOrHo6WA38N4DUhRkFsV4ULLeW%2BEkahRWtoCClKgWvx5FnqSi846ccoZFq2XJ3mq4Pr%2B%2BuNpBXjfyLKsLJTMWvUyG4UYQIvawskjSUhil2VWcFnFebPNU5LkosuQyK15ZtP5%2B%2BlbbRtv9aY76KELxsN2u4%2FVztWXRAhE8BeM7Z7FvwVfgP7SC35vHkh2IOsG5cUqag0MSZ2ma8iExi5ahAm0ljcyDEEflXttEk5F1MrDvnG8SaHqum46HGnbaAB94cr6BRntQxKvqmUX3zisY2y0Z%2BR7YsXEx9uB%2FVH06oZzSsPmEtNd06OtEuZajckRfgVFa3gVp5zzFE%2BaM%2FzCc9v0UHFbLtTNaff3PvkOsVtJp9TDRTbwbpYK8tKjBUliNMe7PnQdJ8F0Knx8p%2F%2F2I878%3D
< 
> GET /idp/profile/SAML2/Redirect/SSO?SAMLRequest=nZJPT%2BMwEMW%2FSuR74iSEf1ZTVKgQlViomi4HLshxpq0lxw6eCQvffp2USOylh72On%2F1%2B741nN5%2BtiT7Ao3a2ZFmSspv5DGVrOrHo6WA38N4DUhRkFsV4ULLeW%2BEkahRWtoCClKgWvx5FnqSi846ccoZFq2XJ3mq4Pr%2B%2BuNpBXjfyLKsLJTMWvUyG4UYQIvawskjSUhil2VWcFnFebPNU5LkosuQyK15ZtP5%2B%2BlbbRtv9aY76KELxsN2u4%2FVztWXRAhE8BeM7Z7FvwVfgP7SC35vHkh2IOsG5cUqag0MSZ2ma8iExi5ahAm0ljcyDEEflXttEk5F1MrDvnG8SaHqum46HGnbaAB94cr6BRntQxKvqmUX3zisY2y0Z%2BR7YsXEx9uB%2FVH06oZzSsPmEtNd06OtEuZajckRfgVFa3gVp5zzFE%2BaM%2FzCc9v0UHFbLtTNaff3PvkOsVtJp9TDRTbwbpYK8tKjBUliNMe7PnQdJ8F0Knx8p%2F%2F2I878%3D HTTP/1.1
> Host: login.itlab.stanford.edu
> 
< HTTP/1.1 302 Found
< Set-Cookie: JSESSIONID=62B9D780E1A2A699147FF2FDB5A7D640; Expires=Tue, 24-Apr-2018 20:27:41 GMT; Path=/idp/; Secure; HttpOnly
< Location: /idp/profile/SAML2/Redirect/SSO;jsessionid=62B9D780E1A2A699147FF2FDB5A7D640?execution=e1s1
< 
> GET /idp/profile/SAML2/Redirect/SSO;jsessionid=62B9D780E1A2A699147FF2FDB5A7D640?execution=e1s1 HTTP/1.1
> Host: login.itlab.stanford.edu
> Cookie: JSESSIONID=62B9D780E1A2A699147FF2FDB5A7D640
> 
< HTTP/1.1 200 OK
< 
--- LOGIN FORM ---
```

**Comment by ekchow** [comment]
I'm having the same issue with the test. I'm getting unauthorized.

localhost:3000/profile bounces to localhost:3000/saml and getting unauthorized.

suSaml-test$ node test.js
Express server listening on port 3000
GET / 304 444.169 ms - -
GET /profile 302 4.206 ms - 54
GET /saml 401 0.715 ms - -

**Comment by ekchow** [comment]
I worked with Scotty and he had updated the code to the latest version 1.1.1. The module is now working. Thanks Scotty!
